(require 'elfeed)
(setq elfeed-feeds
  '(("http://nullprogram.com/feed/" blog emacs)
    ("http://endlessparentheses.com/atom.xml" blog emacs)
    ("https://xkcd.com/atom.xml" comic)
    ("https://hagesumming.no/feed/" blog hage)
    ;("http://planet.lisp.org/rss20.xml" blog lisp)
    ("https://zenhabits.net/feed/" blog mindfulness)
    ("https://www.woodbywright.com/blog?format=RSS" blog woodworking)
    ("https://verktykista.wordpress.com/feed/" blog woodworking)
    ("https://karlfnewmanenterprises.wordpress.com/feed/" blog woodworking)
    ("https://oalannblog.co/feed/" blog woodworking)
    ("https://pfollansbee.wordpress.com/feed/" blog woodworking)
    ("https://hoveloghage.wordpress.com/feed/" blog woodworking)
    ("https://ben.ttm.sh/blog/feed.rss" blog tilde)
    ;("https://readrust.net/all/feed.rss" planet rust)
    ("https://labs.tomasino.org/index.xml" blog tilde)
    ("https://blog.hackeriet.no/feed.xml" hackerspace blog)
    ("http://www.markgtelfer.co.uk/feed/" blog biology)
    ("http://www.biofokus.no/feeds/rss/" biology)))
(global-set-key (kbd "C-x w") 'elfeed)
(add-to-list 'evil-emacs-state-modes 'elfeed-search-mode)
(add-to-list 'evil-emacs-state-modes 'elfeed-show-mode)
(provide 'emacs-elfeed)
